# Generated by Django 4.0 on 2022-01-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserType',
            field=models.BooleanField(default=False),
        ),
    ]
